### PR TITLE
Xcode 12 Support

### PR DESCRIPTION
**Pull request by mRs-**
Xcode 12 needs to specify the Logger with Logging.Logger otherwise it's not finding the right things...

### CODE REVIEW

**Comment by txaiwieser** [comment]
Can we get this merged and a new version released? Thanks! :)

**Comment by chrisaljoudi** [comment]
@txaiwieser Done—0.2.2 is out 😊

**Comment by txaiwieser** [comment]
Thanks!

**Comment by mRs-** [comment]
thansk 🥳

**Pull request merged**
